name: "Tmate Ubuntu SSH"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    steps:
      - name: setup
        run: |
          export TERM=xterm
          wget https://raw.githubusercontent.com/neophyteprjkt/Tmate-Ubuntu/main/dependency.sh
          bash dependency.sh

      - name: tmate ssh (root + cd)
        run: |
          sudo bash -c 'cd && tmate -F'
